const fs=require('fs');
const path=require('path');
const src=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const checks=[];
const add=(name,pass)=>checks.push({name,pass});
add('P08 no generic pago exigible',!/pago exigible/i.test(src));
add('P04 closing copy says Ultimo cierre',src.includes('Último cierre'));
add('P04 account/source cut remains distinct from card close',src.includes('Último corte autoritativo')&&src.includes('Último cierre'));
add('P16 filter says Tipo de evento',src.includes("field('Tipo de evento','type'"));
add('P16 all option says Todos los eventos',src.includes("label:'Todos los eventos'"));
add('P16 calendar dot keyed only by event type',src.includes("class=\"caldot '+(e.type)+'\""));
const legend=(src.match(/<div class="calendarlegend"[^>]*>([\s\S]*?)<\/div>/)||[])[1]||'';
add('P16 legend does not encode Saldado',legend.length>0&&!/Saldado/.test(legend));
add('P16 Calendar/List share one canonical events collection',src.includes('events=calendarEvents().filter')&&src.includes("calendarWidget(events,'calendar')")&&src.includes('events.filter(e=>e.date>=DATA_AS_OF)'));
add('P01 inherited primary logo preserved',src.includes('Pilas_logo_primary_compact_transparent.png'));
add('P14 inherited focus restoration preserved',src.includes('restoreFocusOrigin'));
const failed=checks.filter(x=>!x.pass);
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} ${c.name}`);
const out={ranAt:new Date().toISOString(),checks,passed:checks.length-failed.length,failed:failed.length};
fs.writeFileSync(path.join(__dirname,'f3-calendar-semantics.results.json'),JSON.stringify(out,null,2));
console.log(`\n${out.passed}/${checks.length} checks passed.`);
process.exitCode=failed.length?1:0;
